services:
  idp-db:
    image: postgres:16
    command: "postgres -c max_prepared_transactions=100"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - idp_data:/var/lib/postgresql/data
  idp-user-db:
    image: postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - idp_user_data:/var/lib/postgresql/data
  idp:
    image: keycloak:23.0.6
    build:
      context: .
      dockerfile_inline: |
        FROM quay.io/keycloak/keycloak:23.0.6
        COPY jod-user-storage-23.0.6.jar /opt/keycloak/providers
        COPY quarkus.properties /opt/keycloak/conf/quarkus.properties

    command: "start-dev --import-realm"
    depends_on:
      idp-db:
        condition: service_healthy
      idp-user-db:
        condition: service_healthy
    volumes:
      - ./jod-realm.json:/opt/keycloak/data/import/jod-realm.json
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://idp-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
      - 8443:8443
volumes:
  idp_data:
  idp_user_data:
