spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  threads:
    virtual:
      enabled: true
  security:
    saml2:
      relyingparty:
        registration:
          jodsuomifi:
            signing:
              credentials:
                - private-key-location: "classpath:rp.key"
                  certificate-location: "classpath:rp.crt"
            decryption:
              credentials:
                - private-key-location: "classpath:rp.key"
                  certificate-location: "classpath:rp.crt"
            assertingparty:
              metadata-uri: "https://static.apro.tunnistus.fi/static/metadata/idp-metadata.xml"
              singlesignon:
                binding: "REDIRECT"
                url: "https://testi.apro.tunnistus.fi/idp/profile/SAML2/Redirect/SSO"
              singlelogout:
                binding: "REDIRECT"
                url: "https://testi.apro.tunnistus.fi/idp/profile/SAML2/Redirect/SLO"

springdoc:
  api-docs:
    enabled: true
    path: /openapi/openapi.json
  packages-to-scan: "fi.okm.jod"
  default-produces-media-type: "application/json"
  swagger-ui:
    enabled: "${springdoc.api-docs.enabled:false}"
    validator-url: none
    path: /openapi/openapi.html
    disable-swagger-default-url: true

logging:
  level:
    fi.okm.jod: DEBUG
