logging:
  config: classpath:logback-cloud.xml
  level:
    root: INFO
    fi.okm.jod: INFO

server:
  forward-headers-strategy: native
  shutdown: graceful

springdoc:
  api-docs:
    enabled: false
