server:
  port : 8081

spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/jod
        registration:
          keycloak:
            client-id: yksilo
            scope: openid, profile, email, offline_access

springdoc:
  api-docs:
    enabled: true
    path: /openapi/openapi.json
  packages-to-scan: "fi.okm.jod"
  default-produces-media-type: "application/json"
  swagger-ui:
    enabled: "${springdoc.api-docs.enabled:false}"
    validator-url: none
    path: /openapi/openapi.html
    disable-swagger-default-url: true

logging:
  level:
    fi.okm.jod: DEBUG
