name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs/*.jar

      - uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: build/reports/
